
[[block]]
id = 0
name = "Air"
no_render = true
transparent = true
replacable = true
solid = false
texture = [0, 0, 0]

[[block]]
id = 1
name = "Stone"
texture = [0, 0, 0]
drops = 1

[[block]]
id = 2
name = "Dirt"
texture = [1, 1, 1]
drops = 2

[[block]]
id = 3
name = "Grass"
texture = [3, 2, 1]
drops = 2

[[block]]
id = 4
name = "Log"
flammable = true
texture = [5, 4, 5]
drops = 4

[[block]]
id = 5
name = "Sand"
has_gravity = true
texture = [6, 6, 6]
drops = 5

[[block]]
id = 6
name = "Leaves"
flammable = true
transparent = true
replacable = true
texture = [7, 7, 7]
drops = 6

[[block]]
id = 7
name = "Planks"
flammable = true
texture = [8, 8, 8]
drops = 7

[[block]]
id = 8
name = "Glowstone"
texture = [9, 9, 9]
drops = 8
light = 15

[[item]]
id = 9
name = "Stick"
texture = 15

[[item]]
id = 10
name = "Apple"
texture = 14