
[[block]]
id = "air"
name = "Air"
no_render = true
transparent = true
replacable = true
solid = false
texture = [0, 0, 0]

[[block]]
id = "stone"
name = "Stone"
texture = [0, 0, 0]
drops = "stone"

[[block]]
id = "dirt"
name = "Dirt"
texture = [1, 1, 1]
drops = "dirt"

[[block]]
id = "grass"
name = "Grass"
texture = [3, 2, 1]
drops = "dirt"

[[block]]
id = "log"
name = "Log"
flammable = true
texture = [5, 4, 5]
drops = "log"

[[block]]
id = "sand"
name = "Sand"
has_gravity = true
texture = [6, 6, 6]
drops = "sand"

[[block]]
id = "leaves"
name = "Leaves"
flammable = true
transparent = true
replacable = true
texture = [7, 7, 7]
drops = "stick"

[[block]]
id = "planks"
name = "Planks"
flammable = true
texture = [8, 8, 8]
drops = "planks"

[[block]]
id = "glowstone"
name = "Glowstone"
texture = [9, 9, 9]
drops = "glowstone"
light = 15

[[item]]
id = "stick"
name = "Stick"
texture = 15

[[item]]
id = "apple"
name = "Apple"
texture = 14