
[[shaped]]
input = ["planks"]
output = "stick"
count = 4

[[shaped]]
input = ["log"]
output = "planks"
count = 4

[[shaped]]
input = ["dirt"]
output = "grass"

[[shaped]]
input = [
    "planks", "planks", "planks",
    "planks", "air",    "planks",
    "planks", "planks", "planks",
]
output = "chest"